import type { NutritionTable } from "./nutritionCalc";

/**
 * Per-100g-edible-portion nutrition reference for every ingredient that
 * appears in the catalog longDescriptions. Values are per 100 g of the edible
 * ingredient AS TYPICALLY USED in a dish (cooked chicken breast, olive oil as
 * pure fat, cooked brown rice, etc.), sourced from IFCT 2017 (Indian foods)
 * and USDA FoodData Central, then reviewed by a second pass for gross errors.
 *
 * Generated by the ingredient-nutrition-reference workflow (produce + verify).
 * Composite/vague tokens ("veggies", "sauce/dip of choice") carry low-confidence
 * estimates — the calculator surfaces coverage/confidence so these never get
 * presented as verified macros.
 */
export const NUTRITION_TABLE: NutritionTable = {
  "activated charcoal powder": { kcal: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0, sodiumMg: 0, sugarG: 0 }, // low-confidence estimate
  "almond milk": { kcal: 15, proteinG: 0.5, carbsG: 0.6, fatG: 1.1, fiberG: 0.3, sodiumMg: 63, sugarG: 0.1 },
  "almonds": { kcal: 579, proteinG: 21.2, carbsG: 21.6, fatG: 49.9, fiberG: 12.5, sodiumMg: 1, sugarG: 4.4 },
  "amaranth seeds": { kcal: 371, proteinG: 13.6, carbsG: 65.2, fatG: 7, fiberG: 6.7, sodiumMg: 4, sugarG: 1.7 },
  "apple": { kcal: 52, proteinG: 0.3, carbsG: 13.8, fatG: 0.2, fiberG: 2.4, sodiumMg: 1, sugarG: 10.4 },
  "avocado": { kcal: 160, proteinG: 2, carbsG: 8.5, fatG: 14.7, fiberG: 6.7, sodiumMg: 7, sugarG: 0.7 },
  "babycorn": { kcal: 26, proteinG: 2, carbsG: 5, fatG: 0.2, fiberG: 2, sodiumMg: 5, sugarG: 2 },
  "baking powder": { kcal: 53, proteinG: 0, carbsG: 27.7, fatG: 0, fiberG: 0.2, sodiumMg: 10600, sugarG: 0 },
  "banana": { kcal: 89, proteinG: 1.1, carbsG: 22.8, fatG: 0.3, fiberG: 2.6, sodiumMg: 1, sugarG: 12.2 },
  "barnyard millet poha": { kcal: 346, proteinG: 6.5, carbsG: 74, fatG: 2.2, fiberG: 8, sodiumMg: 5, sugarG: 0.5 }, // low-confidence estimate
  "basil": { kcal: 23, proteinG: 3.2, carbsG: 2.6, fatG: 0.6, fiberG: 1.6, sodiumMg: 4, sugarG: 0.3 },
  "basil pesto": { kcal: 450, proteinG: 5, carbsG: 6, fatG: 45, fiberG: 2, sodiumMg: 800, sugarG: 1.5 }, // low-confidence estimate
  "bbq sauce": { kcal: 172, proteinG: 0.8, carbsG: 41, fatG: 0.6, fiberG: 0.9, sodiumMg: 1027, sugarG: 33 },
  "beetroot": { kcal: 43, proteinG: 1.6, carbsG: 9.6, fatG: 0.2, fiberG: 2.8, sodiumMg: 78, sugarG: 6.8 },
  "bell peppers": { kcal: 26, proteinG: 1, carbsG: 6, fatG: 0.3, fiberG: 2.1, sodiumMg: 4, sugarG: 4.2 },
  "bell peppers & onion": { kcal: 35, proteinG: 1.1, carbsG: 8, fatG: 0.2, fiberG: 1.8, sodiumMg: 4, sugarG: 5 }, // low-confidence estimate
  "blueberries": { kcal: 57, proteinG: 0.7, carbsG: 14.5, fatG: 0.3, fiberG: 2.4, sodiumMg: 1, sugarG: 10 },
  "boiled chickpeas": { kcal: 164, proteinG: 8.9, carbsG: 27.4, fatG: 2.6, fiberG: 7.6, sodiumMg: 7, sugarG: 4.8 },
  "bread slices": { kcal: 265, proteinG: 9, carbsG: 49, fatG: 3.2, fiberG: 2.7, sodiumMg: 490, sugarG: 5 },
  "broccoli": { kcal: 35, proteinG: 2.4, carbsG: 7.2, fatG: 0.4, fiberG: 3.3, sodiumMg: 41, sugarG: 1.4 },
  "brown bread": { kcal: 250, proteinG: 9, carbsG: 47, fatG: 3.5, fiberG: 6, sodiumMg: 450, sugarG: 4.5 },
  "brown rice": { kcal: 112, proteinG: 2.3, carbsG: 23.5, fatG: 0.8, fiberG: 1.8, sodiumMg: 5, sugarG: 0.4 },
  "butter": { kcal: 717, proteinG: 0.9, carbsG: 0.1, fatG: 81, fiberG: 0, sodiumMg: 11, sugarG: 0.1 },
  "button mushrooms": { kcal: 22, proteinG: 3.1, carbsG: 3.3, fatG: 0.3, fiberG: 1, sodiumMg: 5, sugarG: 2 },
  "caesar dressing": { kcal: 542, proteinG: 2.5, carbsG: 3.6, fatG: 57, fiberG: 0.3, sodiumMg: 1000, sugarG: 2.8 },
  "capsicum": { kcal: 26, proteinG: 1, carbsG: 6, fatG: 0.3, fiberG: 2.1, sodiumMg: 4, sugarG: 4.2 },
  "carrot": { kcal: 41, proteinG: 0.9, carbsG: 9.6, fatG: 0.2, fiberG: 2.8, sodiumMg: 69, sugarG: 4.7 },
  "carrot & beans": { kcal: 42, proteinG: 1.6, carbsG: 8.5, fatG: 0.3, fiberG: 3, sodiumMg: 40, sugarG: 3.5 }, // low-confidence estimate
  "cheese": { kcal: 402, proteinG: 25, carbsG: 1.3, fatG: 33, fiberG: 0, sodiumMg: 621, sugarG: 0.5 },
  "cheese sauce": { kcal: 197, proteinG: 7, carbsG: 7, fatG: 16, fiberG: 0.3, sodiumMg: 650, sugarG: 3 },
  "cherry tomatoes": { kcal: 18, proteinG: 0.9, carbsG: 3.9, fatG: 0.2, fiberG: 1.2, sodiumMg: 5, sugarG: 2.6 },
  "chia seeds": { kcal: 486, proteinG: 16.5, carbsG: 42, fatG: 30.7, fiberG: 34.4, sodiumMg: 16, sugarG: 0 },
  "chicken": { kcal: 215, proteinG: 26, carbsG: 0, fatG: 13, fiberG: 0, sodiumMg: 70, sugarG: 0 },
  "chicken breast": { kcal: 165, proteinG: 31, carbsG: 0, fatG: 3.6, fiberG: 0, sodiumMg: 74, sugarG: 0 },
  "chicken strips": { kcal: 175, proteinG: 29, carbsG: 1, fatG: 6, fiberG: 0, sodiumMg: 80, sugarG: 0 },
  "chicken tikka": { kcal: 195, proteinG: 25, carbsG: 4, fatG: 9, fiberG: 0.5, sodiumMg: 420, sugarG: 2 },
  "chickpeas": { kcal: 164, proteinG: 9, carbsG: 27, fatG: 2.6, fiberG: 7.6, sodiumMg: 7, sugarG: 4.8 },
  "chili flakes": { kcal: 282, proteinG: 12, carbsG: 50, fatG: 14, fiberG: 28, sodiumMg: 30, sugarG: 10 },
  "chili paste": { kcal: 90, proteinG: 3, carbsG: 15, fatG: 2, fiberG: 6, sodiumMg: 2200, sugarG: 6 }, // low-confidence estimate
  "chipotle sauce": { kcal: 180, proteinG: 1.5, carbsG: 12, fatG: 14, fiberG: 1.5, sodiumMg: 900, sugarG: 6 }, // low-confidence estimate
  "cinnamon powder": { kcal: 247, proteinG: 4, carbsG: 81, fatG: 1.2, fiberG: 53, sodiumMg: 10, sugarG: 2.2 },
  "cocoa powder": { kcal: 228, proteinG: 19.6, carbsG: 58, fatG: 13.7, fiberG: 37, sodiumMg: 21, sugarG: 1.8 },
  "coriander leaves": { kcal: 23, proteinG: 2.1, carbsG: 3.7, fatG: 0.5, fiberG: 2.8, sodiumMg: 46, sugarG: 0.9 },
  "cornstarch slurry": { kcal: 60, proteinG: 0, carbsG: 15, fatG: 0, fiberG: 0, sodiumMg: 2, sugarG: 0 }, // low-confidence estimate
  "crispy peri peri chicken": { kcal: 260, proteinG: 22, carbsG: 12, fatG: 14, fiberG: 1, sodiumMg: 650, sugarG: 2 },
  "crispy peri peri mushrooms": { kcal: 190, proteinG: 4, carbsG: 18, fatG: 12, fiberG: 2, sodiumMg: 520, sugarG: 2 },
  "croutons": { kcal: 407, proteinG: 9, carbsG: 64, fatG: 13, fiberG: 4, sodiumMg: 700, sugarG: 3 },
  "cucumber": { kcal: 15, proteinG: 0.7, carbsG: 3.6, fatG: 0.1, fiberG: 0.5, sodiumMg: 2, sugarG: 1.7 },
  "curd": { kcal: 60, proteinG: 3.1, carbsG: 4.4, fatG: 4, fiberG: 0, sodiumMg: 36, sugarG: 4.4 },
  "curry leaves": { kcal: 66, proteinG: 6.1, carbsG: 18.7, fatG: 1, fiberG: 6.4, sodiumMg: 13, sugarG: 0 },
  "dates": { kcal: 283, proteinG: 2.5, carbsG: 75, fatG: 0.4, fiberG: 8, sodiumMg: 2, sugarG: 63 },
  "dates puree": { kcal: 280, proteinG: 2.4, carbsG: 74, fatG: 0.4, fiberG: 7.5, sodiumMg: 3, sugarG: 63 },
  "diet coke can": { kcal: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0, sodiumMg: 4, sugarG: 0 },
  "dry red chili flakes": { kcal: 282, proteinG: 12, carbsG: 50, fatG: 14, fiberG: 28, sodiumMg: 30, sugarG: 10 },
  "dry yeast": { kcal: 325, proteinG: 40, carbsG: 41, fatG: 7.6, fiberG: 27, sodiumMg: 51, sugarG: 0 },
  "egg": { kcal: 143, proteinG: 13, carbsG: 0.7, fatG: 9.5, fiberG: 0, sodiumMg: 142, sugarG: 0.4 },
  "egg whites": { kcal: 52, proteinG: 11, carbsG: 0.7, fatG: 0.2, fiberG: 0, sodiumMg: 166, sugarG: 0.7 },
  "eggs": { kcal: 143, proteinG: 13, carbsG: 0.7, fatG: 9.5, fiberG: 0, sodiumMg: 142, sugarG: 0.4 },
  "falafel": { kcal: 333, proteinG: 13.3, carbsG: 31.8, fatG: 17.8, fiberG: 4.9, sodiumMg: 294, sugarG: 0 },
  "feta cheese": { kcal: 264, proteinG: 14.2, carbsG: 4.1, fatG: 21.3, fiberG: 0, sodiumMg: 917, sugarG: 4.1 },
  "flattened rice (poha)": { kcal: 346, proteinG: 6.6, carbsG: 77.3, fatG: 1.2, fiberG: 2.5, sodiumMg: 6, sugarG: 0 },
  "fresh cream": { kcal: 292, proteinG: 2.3, carbsG: 3.4, fatG: 30, fiberG: 0, sodiumMg: 32, sugarG: 3 },
  "fresh mint": { kcal: 48, proteinG: 4.8, carbsG: 5.8, fatG: 0.7, fiberG: 6.8, sodiumMg: 26, sugarG: 0 },
  "garlic": { kcal: 145, proteinG: 6.3, carbsG: 29, fatG: 0.5, fiberG: 4.9, sodiumMg: 17, sugarG: 1 },
  "ginger": { kcal: 80, proteinG: 2.3, carbsG: 17.8, fatG: 0.9, fiberG: 2.4, sodiumMg: 13, sugarG: 1.7 },
  "grapes": { kcal: 67, proteinG: 0.6, carbsG: 16.5, fatG: 0.3, fiberG: 0.9, sodiumMg: 2, sugarG: 15.5 },
  "green apple": { kcal: 52, proteinG: 0.3, carbsG: 13.8, fatG: 0.2, fiberG: 2.4, sodiumMg: 1, sugarG: 10.4 },
  "green chili": { kcal: 40, proteinG: 2, carbsG: 8.8, fatG: 0.4, fiberG: 3, sodiumMg: 4, sugarG: 5.1 },
  "green tea (brewed & cooled)": { kcal: 1, proteinG: 0, carbsG: 0.2, fatG: 0, fiberG: 0, sodiumMg: 1, sugarG: 0 },
  "grilled bell peppers, zucchini, onions": { kcal: 42, proteinG: 1.5, carbsG: 8, fatG: 0.5, fiberG: 2, sodiumMg: 6, sugarG: 4.5 }, // low-confidence estimate
  "grilled chicken": { kcal: 165, proteinG: 31, carbsG: 0, fatG: 3.6, fiberG: 0, sodiumMg: 74, sugarG: 0 },
  "grilled chicken breast": { kcal: 165, proteinG: 31, carbsG: 0, fatG: 3.6, fiberG: 0, sodiumMg: 74, sugarG: 0 },
  "honey": { kcal: 304, proteinG: 0.3, carbsG: 82, fatG: 0, fiberG: 0, sodiumMg: 4, sugarG: 82 },
  "hummus": { kcal: 166, proteinG: 7.9, carbsG: 14.3, fatG: 9.6, fiberG: 6, sodiumMg: 379, sugarG: 0.4 },
  "hung curd": { kcal: 98, proteinG: 9, carbsG: 4, fatG: 5, fiberG: 0, sodiumMg: 40, sugarG: 4 },
  "ice cubes": { kcal: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0, sodiumMg: 0, sugarG: 0 },
  "jalapeños": { kcal: 29, proteinG: 0.9, carbsG: 6.5, fatG: 0.4, fiberG: 2.8, sodiumMg: 3, sugarG: 4.1 },
  "lemon juice": { kcal: 22, proteinG: 0.4, carbsG: 6.9, fatG: 0.2, fiberG: 0.3, sodiumMg: 1, sugarG: 2.5 },
  "lettuce": { kcal: 15, proteinG: 1.4, carbsG: 2.9, fatG: 0.2, fiberG: 1.3, sodiumMg: 28, sugarG: 0.8 },
  "lettuce, cucumber, tomato": { kcal: 16, proteinG: 1, carbsG: 3.4, fatG: 0.2, fiberG: 1.1, sodiumMg: 14, sugarG: 2 }, // low-confidence estimate
  "mashed potato": { kcal: 113, proteinG: 2, carbsG: 17, fatG: 4.2, fiberG: 1.5, sodiumMg: 320, sugarG: 1.8 },
  "mayo/yogurt dip": { kcal: 230, proteinG: 2.5, carbsG: 6, fatG: 22, fiberG: 0, sodiumMg: 450, sugarG: 3 }, // low-confidence estimate
  "milk": { kcal: 62, proteinG: 3.2, carbsG: 4.7, fatG: 3.3, fiberG: 0, sodiumMg: 44, sugarG: 4.7 },
  "milk/cream": { kcal: 130, proteinG: 2.9, carbsG: 4.2, fatG: 11.5, fiberG: 0, sodiumMg: 40, sugarG: 4.2 }, // low-confidence estimate
  "millet flour": { kcal: 348, proteinG: 10.5, carbsG: 67, fatG: 4.2, fiberG: 8, sodiumMg: 5, sugarG: 1 },
  "mini pita breads": { kcal: 275, proteinG: 9, carbsG: 55, fatG: 1.2, fiberG: 2.2, sodiumMg: 530, sugarG: 1.5 },
  "mint chutney": { kcal: 80, proteinG: 3, carbsG: 12, fatG: 1.5, fiberG: 4, sodiumMg: 600, sugarG: 3 }, // low-confidence estimate
  "mint leaves": { kcal: 48, proteinG: 3.8, carbsG: 8, fatG: 0.7, fiberG: 6.8, sodiumMg: 30, sugarG: 0 },
  "mixed veggies (cabbage, carrot, beans)": { kcal: 38, proteinG: 2, carbsG: 7.5, fatG: 0.3, fiberG: 3, sodiumMg: 40, sugarG: 3.5 }, // low-confidence estimate
  "moong dal": { kcal: 348, proteinG: 24, carbsG: 59, fatG: 1.2, fiberG: 8, sodiumMg: 30, sugarG: 2 },
  "moong sprouts": { kcal: 102, proteinG: 7.6, carbsG: 18, fatG: 0.5, fiberG: 7.6, sodiumMg: 15, sugarG: 2 },
  "multigrain bread": { kcal: 265, proteinG: 10, carbsG: 45, fatG: 4, fiberG: 6, sodiumMg: 450, sugarG: 4 },
  "mushrooms": { kcal: 26, proteinG: 3.1, carbsG: 4, fatG: 0.3, fiberG: 1.3, sodiumMg: 6, sugarG: 1.5 },
  "mustard seeds": { kcal: 508, proteinG: 26, carbsG: 28, fatG: 36, fiberG: 12, sodiumMg: 13, sugarG: 6.8 },
  "nachos chips": { kcal: 497, proteinG: 7, carbsG: 63, fatG: 24, fiberG: 4, sodiumMg: 560, sugarG: 1.5 },
  "nutella": { kcal: 539, proteinG: 6, carbsG: 57, fatG: 31, fiberG: 3.5, sodiumMg: 41, sugarG: 56 },
  "oats": { kcal: 389, proteinG: 16.9, carbsG: 66.3, fatG: 6.9, fiberG: 10.6, sodiumMg: 2, sugarG: 1 },
  "oil": { kcal: 884, proteinG: 0, carbsG: 0, fatG: 100, fiberG: 0, sodiumMg: 0, sugarG: 0 },
  "olive oil": { kcal: 884, proteinG: 0, carbsG: 0, fatG: 100, fiberG: 0, sodiumMg: 2, sugarG: 0 },
  "olives": { kcal: 115, proteinG: 0.8, carbsG: 6.3, fatG: 10.7, fiberG: 3.2, sodiumMg: 1556, sugarG: 0 },
  "onion": { kcal: 40, proteinG: 1.1, carbsG: 9.3, fatG: 0.1, fiberG: 1.7, sodiumMg: 4, sugarG: 4.2 },
  "onion & bell pepper": { kcal: 34, proteinG: 1, carbsG: 7.5, fatG: 0.2, fiberG: 1.8, sodiumMg: 4, sugarG: 4 }, // low-confidence estimate
  "onion & capsicum": { kcal: 34, proteinG: 1, carbsG: 7.5, fatG: 0.2, fiberG: 1.8, sodiumMg: 4, sugarG: 4 }, // low-confidence estimate
  "onion & cucumber": { kcal: 27, proteinG: 0.9, carbsG: 6, fatG: 0.1, fiberG: 1.2, sodiumMg: 4, sugarG: 3 }, // low-confidence estimate
  "onion & tomato slices": { kcal: 31, proteinG: 1, carbsG: 6.9, fatG: 0.2, fiberG: 1.4, sodiumMg: 5, sugarG: 3.6 }, // low-confidence estimate
  "onion rings": { kcal: 332, proteinG: 4.6, carbsG: 39, fatG: 17.8, fiberG: 1.7, sodiumMg: 410, sugarG: 4 },
  "orange segments": { kcal: 47, proteinG: 0.9, carbsG: 11.8, fatG: 0.1, fiberG: 2.4, sodiumMg: 0, sugarG: 9.4 },
  "paneer": { kcal: 296, proteinG: 18.3, carbsG: 1.2, fatG: 25.1, fiberG: 0, sodiumMg: 22, sugarG: 1.2 },
  "paneer tikka": { kcal: 270, proteinG: 17, carbsG: 6, fatG: 20, fiberG: 1, sodiumMg: 400, sugarG: 3 },
  "papaya": { kcal: 43, proteinG: 0.5, carbsG: 10.8, fatG: 0.3, fiberG: 1.7, sodiumMg: 8, sugarG: 7.8 },
  "paprika": { kcal: 282, proteinG: 14.1, carbsG: 54, fatG: 12.9, fiberG: 34.9, sodiumMg: 68, sugarG: 10.3 },
  "parmesan": { kcal: 392, proteinG: 35.8, carbsG: 3.2, fatG: 25.8, fiberG: 0, sodiumMg: 1529, sugarG: 0.8 },
  "parmesan cheese": { kcal: 392, proteinG: 35.8, carbsG: 3.2, fatG: 25.8, fiberG: 0, sodiumMg: 1529, sugarG: 0.8 },
  "parsley": { kcal: 36, proteinG: 3, carbsG: 6.3, fatG: 0.8, fiberG: 3.3, sodiumMg: 56, sugarG: 0.9 },
  "pasta": { kcal: 158, proteinG: 5.8, carbsG: 30.9, fatG: 0.9, fiberG: 1.8, sodiumMg: 1, sugarG: 0.6 },
  "peanut butter": { kcal: 588, proteinG: 25.1, carbsG: 20, fatG: 50, fiberG: 6, sodiumMg: 459, sugarG: 9.2 },
  "peanuts": { kcal: 567, proteinG: 25.8, carbsG: 16.1, fatG: 49.2, fiberG: 8.5, sodiumMg: 18, sugarG: 4 },
  "penne pasta": { kcal: 158, proteinG: 5.8, carbsG: 30.9, fatG: 0.9, fiberG: 1.8, sodiumMg: 1, sugarG: 0.6 },
  "peri peri mayo": { kcal: 680, proteinG: 1, carbsG: 6, fatG: 73, fiberG: 0.5, sodiumMg: 650, sugarG: 3 },
  "peri peri sauce": { kcal: 95, proteinG: 1.5, carbsG: 12, fatG: 4, fiberG: 1.5, sodiumMg: 1200, sugarG: 7 },
  "pita bread": { kcal: 275, proteinG: 9.1, carbsG: 55.7, fatG: 1.2, fiberG: 2.2, sodiumMg: 536, sugarG: 1.3 },
  "poached egg": { kcal: 143, proteinG: 12.5, carbsG: 0.7, fatG: 9.9, fiberG: 0, sodiumMg: 142, sugarG: 0.4 },
  "pomegranate": { kcal: 83, proteinG: 1.7, carbsG: 18.7, fatG: 1.2, fiberG: 4, sodiumMg: 3, sugarG: 13.7 },
  "potato wedges": { kcal: 180, proteinG: 3, carbsG: 26, fatG: 7, fiberG: 2.5, sodiumMg: 330, sugarG: 1 },
  "prawns": { kcal: 99, proteinG: 21, carbsG: 0.9, fatG: 1.4, fiberG: 0, sodiumMg: 220, sugarG: 0 },
  "quinoa": { kcal: 120, proteinG: 4.4, carbsG: 21.3, fatG: 1.9, fiberG: 2.8, sodiumMg: 7, sugarG: 0.9 },
  "ragi flour": { kcal: 320, proteinG: 7.2, carbsG: 66.8, fatG: 1.9, fiberG: 11.2, sodiumMg: 11, sugarG: 0.9 },
  "ranch yogurt dip": { kcal: 140, proteinG: 3, carbsG: 6, fatG: 11, fiberG: 0.3, sodiumMg: 450, sugarG: 3 },
  "ranch yogurt dressing": { kcal: 110, proteinG: 3, carbsG: 6, fatG: 8, fiberG: 0, sodiumMg: 600, sugarG: 4 },
  "ranch/mayo": { kcal: 500, proteinG: 1.5, carbsG: 5, fatG: 52, fiberG: 0, sodiumMg: 700, sugarG: 3 }, // low-confidence estimate
  "rice": { kcal: 130, proteinG: 2.7, carbsG: 28, fatG: 0.3, fiberG: 0.4, sodiumMg: 1, sugarG: 0.1 },
  "romaine lettuce": { kcal: 17, proteinG: 1.2, carbsG: 3.3, fatG: 0.3, fiberG: 2.1, sodiumMg: 8, sugarG: 1.2 },
  "salsa": { kcal: 36, proteinG: 1.5, carbsG: 7, fatG: 0.2, fiberG: 1.8, sodiumMg: 430, sugarG: 4 },
  "salt": { kcal: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0, sodiumMg: 38758, sugarG: 0 },
  "salt & black pepper": { kcal: 10, proteinG: 0.3, carbsG: 2, fatG: 0.1, fiberG: 0.8, sodiumMg: 35000, sugarG: 0 }, // low-confidence estimate
  "salt & pepper": { kcal: 10, proteinG: 0.3, carbsG: 2, fatG: 0.1, fiberG: 0.8, sodiumMg: 35000, sugarG: 0 }, // low-confidence estimate
  "salt & turmeric": { kcal: 15, proteinG: 0.4, carbsG: 3, fatG: 0.2, fiberG: 1, sodiumMg: 32000, sugarG: 0.2 }, // low-confidence estimate
  "sauce": { kcal: 100, proteinG: 1.5, carbsG: 12, fatG: 5, fiberG: 0.5, sodiumMg: 800, sugarG: 6 }, // low-confidence estimate
  "sauce/dip of choice": { kcal: 150, proteinG: 2, carbsG: 10, fatG: 11, fiberG: 0.5, sodiumMg: 600, sugarG: 5 }, // low-confidence estimate
  "sautéed broccoli, zucchini, carrots": { kcal: 80, proteinG: 2, carbsG: 8, fatG: 5, fiberG: 2.5, sodiumMg: 150, sugarG: 4 }, // low-confidence estimate
  "smoked chicken": { kcal: 180, proteinG: 28, carbsG: 1, fatG: 7, fiberG: 0, sodiumMg: 700, sugarG: 0 },
  "soda water": { kcal: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0, sodiumMg: 5, sugarG: 0 },
  "sour cream": { kcal: 198, proteinG: 2.4, carbsG: 4.6, fatG: 19, fiberG: 0, sodiumMg: 50, sugarG: 3.5 },
  "soy sauce": { kcal: 53, proteinG: 8, carbsG: 5, fatG: 0.6, fiberG: 0.8, sodiumMg: 5493, sugarG: 0.4 },
  "spaghetti pasta": { kcal: 158, proteinG: 5.8, carbsG: 31, fatG: 0.9, fiberG: 1.8, sodiumMg: 1, sugarG: 0.6 },
  "spinach": { kcal: 23, proteinG: 2.9, carbsG: 3.6, fatG: 0.4, fiberG: 2.2, sodiumMg: 79, sugarG: 0.4 },
  "steamed broccoli & carrots": { kcal: 38, proteinG: 2.2, carbsG: 7.5, fatG: 0.4, fiberG: 3, sodiumMg: 45, sugarG: 3 }, // low-confidence estimate
  "steamed vegetables": { kcal: 38, proteinG: 2, carbsG: 7, fatG: 0.4, fiberG: 3, sodiumMg: 40, sugarG: 3 }, // low-confidence estimate
  "steamed veggies": { kcal: 38, proteinG: 2, carbsG: 7, fatG: 0.4, fiberG: 3, sodiumMg: 40, sugarG: 3 }, // low-confidence estimate
  "stevia/sugar": { kcal: 200, proteinG: 0, carbsG: 50, fatG: 0, fiberG: 0, sodiumMg: 1, sugarG: 40 }, // low-confidence estimate
  "sugar": { kcal: 387, proteinG: 0, carbsG: 100, fatG: 0, fiberG: 0, sodiumMg: 1, sugarG: 100 },
  "thums up can": { kcal: 44, proteinG: 0, carbsG: 11, fatG: 0, fiberG: 0, sodiumMg: 5, sugarG: 11 },
  "tofu": { kcal: 76, proteinG: 8.1, carbsG: 1.9, fatG: 4.8, fiberG: 0.3, sodiumMg: 7, sugarG: 0.6 },
  "tomato": { kcal: 18, proteinG: 0.9, carbsG: 3.9, fatG: 0.2, fiberG: 1.2, sodiumMg: 5, sugarG: 2.6 },
  "tomato puree": { kcal: 38, proteinG: 1.6, carbsG: 8.9, fatG: 0.2, fiberG: 1.9, sodiumMg: 28, sugarG: 5.5 },
  "tortilla": { kcal: 304, proteinG: 8, carbsG: 49, fatG: 8, fiberG: 3, sodiumMg: 440, sugarG: 2 },
  "tortilla/pita": { kcal: 260, proteinG: 8, carbsG: 48, fatG: 3, fiberG: 2.5, sodiumMg: 460, sugarG: 1.5 }, // low-confidence estimate
  "veg stock / water": { kcal: 6, proteinG: 0.3, carbsG: 1, fatG: 0.1, fiberG: 0, sodiumMg: 300, sugarG: 0.5 }, // low-confidence estimate
  "veggies": { kcal: 40, proteinG: 2, carbsG: 8, fatG: 0.3, fiberG: 2.8, sodiumMg: 30, sugarG: 3.5 }, // low-confidence estimate
  "vinegar": { kcal: 18, proteinG: 0, carbsG: 0.6, fatG: 0, fiberG: 0, sodiumMg: 2, sugarG: 0.4 },
  "warm water": { kcal: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0, sodiumMg: 0, sugarG: 0 },
  "water": { kcal: 0, proteinG: 0, carbsG: 0, fatG: 0, fiberG: 0, sodiumMg: 0, sugarG: 0 },
  "watermelon cubes": { kcal: 30, proteinG: 0.6, carbsG: 7.6, fatG: 0.2, fiberG: 0.4, sodiumMg: 1, sugarG: 6.2 },
  "whey protein": { kcal: 400, proteinG: 80, carbsG: 8, fatG: 6, fiberG: 0, sodiumMg: 300, sugarG: 5 },
  "white bread": { kcal: 265, proteinG: 9, carbsG: 49, fatG: 3.2, fiberG: 2.7, sodiumMg: 490, sugarG: 5 },
  "whole grain bread": { kcal: 250, proteinG: 13, carbsG: 43, fatG: 3.5, fiberG: 6, sodiumMg: 450, sugarG: 6 },
  "whole wheat flour": { kcal: 341, proteinG: 12, carbsG: 69, fatG: 1.5, fiberG: 11, sodiumMg: 2, sugarG: 0.5 },
  "whole wheat tortilla": { kcal: 310, proteinG: 8, carbsG: 51, fatG: 7, fiberG: 5, sodiumMg: 550, sugarG: 2 },
  "yogurt": { kcal: 60, proteinG: 3.1, carbsG: 4.7, fatG: 4, fiberG: 0, sodiumMg: 45, sugarG: 4.7 },
  "yogurt dressing": { kcal: 100, proteinG: 3, carbsG: 6, fatG: 7, fiberG: 0, sodiumMg: 300, sugarG: 4 }, // low-confidence estimate
  "zucchini, bell peppers, broccoli": { kcal: 28, proteinG: 2, carbsG: 5, fatG: 0.3, fiberG: 2, sodiumMg: 15, sugarG: 2.5 }, // low-confidence estimate
};
