import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminAuthRouter from "./adminAuth";
import adminStatusRouter from "./adminStatus";
import errorReportRouter from "./errorReport";
import deliveryRouter from "./delivery";
import fulfillmentRouter from "./fulfillment";
import userAddressesRouter from "./userAddresses";
import supportAgentRouter from "./supportAgent";
import coachAgentRouter from "./coachAgent";
import opsRouter from "./ops";
import subscriptionsRouter from "./subscriptions";
import loyaltyRouter from "./loyalty";
import preferencesRouter from "./preferences";
import userConsentsRouter from "./userConsents";
import rdAdvisoryRouter from "./rdAdvisory";
import bundlesRouter from "./bundles";
import groupOrdersRouter from "./groupOrders";
import wellnessRouter from "./wellness";
import aiRunsRouter from "./aiRuns";
import opsAgentRouter from "./opsAgent";
import forecastingRouter from "./forecasting";
import menuRouter from "./menu";
import menuAssetsRouter from "./menuAssets";
import cmsAgentRouter from "./cmsAgent";
import menuEngineeringRouter from "./menuEngineering";
import analyticsRouter from "./analytics";
import supportTicketsRouter from "./supportTickets";
import recipesRouter from "./recipes";
import teamProfilesRouter from "./teamProfiles";
import challengesRouter from "./challenges";
import rdPartnersRouter from "./rdPartners";
import corporateRouter from "./corporate";
import corporateLeadsRouter from "./corporateLeads";
import addonsRouter from "./addons";
import premiumRouter from "./premium";
import marketplaceRouter from "./marketplace";
import dishRationalesRouter from "./dishRationales";
import mealPlansRouter from "./mealPlans";
import rdCopilotRouter from "./rdCopilot";
import communityRouter from "./community";
import b2bPlannerRouter from "./b2bPlanner";
import ordersRouter from "./orders";
import checkoutRouter from "./checkout";
import paymentsRouter from "./payments";
import refundsRouter from "./refunds";
import vitalsRouter from "./vitals";
import eventsRouter from "./events";
import complianceRouter from "./compliance";
import petpoojaRouter from "./petpooja";
import { petpoojaWebhooksMounted } from "../lib/petpoojaClient";
import wearableRouter from "./wearable";
import catalogRouter from "./catalog";
import cspReportRouter from "./cspReport";
import openApiContractRouter from "./openApiContract";
import geoRouter from "./geo";
import ecosystemRouter from "./ecosystem";
import savedMealsRouter from "./savedMeals";
import serviceabilityRouter from "./serviceability";
import serviceabilityInterestRouter from "./serviceabilityInterest";

const router: IRouter = Router();

router.use(healthRouter);
router.use(catalogRouter);
router.use(cspReportRouter);
router.use(openApiContractRouter);
router.use(geoRouter);
router.use(serviceabilityRouter);
router.use(serviceabilityInterestRouter);
router.use(authRouter);
router.use(adminAuthRouter);
router.use(adminStatusRouter);
router.use(errorReportRouter);
router.use(deliveryRouter);
router.use(fulfillmentRouter);
router.use(userAddressesRouter);
router.use(supportAgentRouter);
router.use(coachAgentRouter);
router.use("/ops", opsRouter);
router.use(subscriptionsRouter);
router.use(loyaltyRouter);
router.use(preferencesRouter);
router.use(userConsentsRouter);
router.use(rdAdvisoryRouter);
router.use(bundlesRouter);
router.use(groupOrdersRouter);
router.use(wellnessRouter);
router.use(aiRunsRouter);
router.use(opsAgentRouter);
router.use(forecastingRouter);
router.use(menuRouter);
router.use(menuAssetsRouter);
router.use(cmsAgentRouter);
router.use(menuEngineeringRouter);
router.use(analyticsRouter);
router.use(supportTicketsRouter);
router.use(recipesRouter);
router.use(teamProfilesRouter);
router.use(challengesRouter);
router.use(rdPartnersRouter);
router.use(corporateRouter);
router.use(corporateLeadsRouter);
router.use(addonsRouter);
router.use(premiumRouter);
router.use(marketplaceRouter);
router.use(dishRationalesRouter);
router.use(mealPlansRouter);
router.use(rdCopilotRouter);
router.use(communityRouter);
router.use(b2bPlannerRouter);
router.use(ordersRouter);
router.use(checkoutRouter);
router.use(paymentsRouter);
router.use(refundsRouter);
router.use(vitalsRouter);
router.use(eventsRouter);
router.use(complianceRouter);
// Petpooja's inbound webhook surface is mounted only when the integration is
// actually configured. Decommissioning means UNMOUNTING (PETPOOJA_WEBHOOKS_ENABLED=false
// or simply not configuring it), not blanking PETPOOJA_* env and leaving the
// routes reachable — see the SECURITY CORRECTION note in lib/petpoojaClient.ts.
if (petpoojaWebhooksMounted()) {
  router.use(petpoojaRouter);
}
router.use(wearableRouter);
router.use(ecosystemRouter);
router.use(savedMealsRouter);

export default router;
