import type { LegalDoc } from "./types";
import { COMPANY as C } from "./company";

/**
 * Health & Nutrition Disclaimer. The wellness/clinical-adjacent surfaces — the
 * AI coach, advisory sessions, macros, and allergen handling — need a clear "general
 * information, not medical advice" boundary and an allergen/cross-contact
 * caveat that matches the shared-kitchen reality.
 */
export const disclaimerDoc: LegalDoc = {
  slug: "disclaimer",
  title: "Health & Nutrition Disclaimer",
  summary:
    "Tanmatra provides food and general nutrition information, not medical advice. Please read how our nutrition data, coach, advisory sessions, and allergen handling work.",
  updated: C.updated,
  sections: [
    {
      heading: "1. General information, not medical advice",
      body: [
        `${C.brand}, operated by ${C.legalName}, provides food and general nutrition information for healthy adults. Nothing on the Platform is medical advice, diagnosis, or treatment, and it is not a substitute for care from a qualified doctor or healthcare professional. Always seek professional advice for any medical condition or before making significant dietary changes.`,
      ],
    },
    {
      heading: "2. The nutrition coach",
      body: [
        "The nutrition coach offers general, educational nutrition guidance generated by an AI system. It is designed to decline clinical questions and to direct you to a qualified healthcare professional instead. It does not diagnose, treat, or prescribe, and you should not rely on it for medical decisions.",
      ],
    },
    {
      heading: "3. Advisory sessions",
      body: [
        "Where we offer bookable sessions, they provide general advisory guidance about food and nutrition. A session is not a consultation with a medical doctor, does not create a doctor–patient relationship, and is not for emergencies or the management of medical conditions in place of your treating physician.",
      ],
    },
    {
      heading: "4. Nutrition and macro information",
      body: [
        "Calorie, macro, and ingredient information is provided in good faith to help you choose and may be an estimate. Actual values vary with natural ingredients, portioning, and preparation. If precise nutritional values matter for a medical reason, confirm them with your healthcare professional.",
      ],
    },
    {
      heading: "5. Allergens and dietary restrictions — please read",
      body: [
        "We label allergens and let you set foods to avoid, and our systems filter recommendations accordingly. However, our meals are prepared and packed in a shared kitchen that handles common allergens (which may include milk, tree nuts, peanuts, soy, wheat/gluten, sesame, and others), so cross-contact can occur and we cannot guarantee any meal is free from a given allergen.",
        "If you have a food allergy, intolerance, or medical dietary need — especially a severe or life-threatening allergy — do not rely solely on the Platform's filters. Check the information provided, exercise your own judgement, and consult your doctor. If you experience an allergic reaction or any medical emergency, stop eating and seek immediate medical help.",
      ],
    },
    {
      heading: "6. Individual results vary",
      body: [
        "Nutrition and wellness outcomes differ from person to person. Any goals, plans, or suggestions are general and not a promise of a particular result. People who are pregnant or nursing, have a medical condition, or take medication should consult a healthcare professional before changing their diet.",
      ],
    },
    {
      heading: "7. Emergencies",
      body: [
        "The Platform is not for medical emergencies. If you have a medical emergency, contact your doctor or your local emergency services immediately.",
      ],
    },
    {
      heading: "8. Liability",
      body: [
        "To the fullest extent permitted by law, we are not liable for decisions you make in reliance on general information provided on the Platform. This disclaimer forms part of, and should be read with, our Terms of Service.",
      ],
    },
  ],
};
