#!/usr/bin/env python3
"""
stitch_retoken.py — Stitch export → .tnm2-skinned pixel-diff REFERENCE.

Purpose: manufacture the target for pixel-parity CI. The output is a
REFERENCE ARTIFACT, never shipped code (it keeps Tailwind CDN and the
Material Symbols icon font so glyph geometry survives for diffing;
production uses compiled tnm2 components + inline SVG).

Four gates, in order:
  1. TOKEN    — Nocturnal palette + fonts → .tnm2 values
  2. BRAND    — NUTRIENG / stray brand strings → TANMATRA
  3. CURRENCY — $ → ₹ (symbol only; amounts flagged, not converted)
  4. CLAIMS   — treat/cure/prevent/guarantee language → compliant phrasing

Usage:  python3 stitch_retoken.py IN.html OUT.html
Exit report lists every substitution count so nothing changes silently.
"""
import re, sys, collections

# ── Gate 1 · TOKEN ──────────────────────────────────────────────────────
# Nocturnal Nourishment → .tnm2 (saffron #E89A3E confirmed; alert #DC8773
# per brief §1; ink/sage/caution are the prototype placeholders — update
# this table once theme.css values are swapped in, nothing else changes).
HEX_MAP = {
    # amber ramp → saffron ramp
    "#fbbf24": "#E89A3E", "#f9bd22": "#E89A3E",
    "#ffe1a7": "#F2C489", "#ffdf9f": "#F2C489",
    "#795900": "#8A5A22", "#6c4f00": "#8A5A22",
    "#5c4300": "#221302", "#402d00": "#221302", "#261a00": "#221302",
    # neutrals → clinical ink ladder
    "#000000": "#0A0D0F", "#0e0e0e": "#0A0D0F", "#131313": "#10161A",
    "#1b1b1b": "#171F25", "#1f1f1f": "#171F25", "#2a2a2a": "#1E2830",
    "#303030": "#1E2830", "#353535": "#1E2830", "#454747": "#1E2830",
    "#4f4633": "#1E2830",
    # text neutrals
    "#e2e2e2": "#F1EEE8", "#c6c6c7": "#A9B2B7", "#d3c5ac": "#A9B2B7",
    "#9c8f79": "#77828A", "#b4b5b5": "#A9B2B7",
    # tertiary cyan → sage (info/positive role in .tnm2 semantics)
    "#34daff": "#8CBB9B",
    # Material dark error → brief error
    "#ffb4ab": "#DC8773", "#93000a": "#3A1F1B", "#690005": "#3A1F1B",
    "#ffdad6": "#F2D2C9",
}
FONT_MAP = [
    (re.compile(r"Geist", re.I), "Inter"),
    (re.compile(r"Space Grotesk", re.I), "Inter"),
]

# ── Gate 2 · BRAND ──────────────────────────────────────────────────────
BRAND_MAP = [
    (re.compile(r"NUTRIENG", re.I), "TANMATRA"),
    (re.compile(r"Nocturnal Nourishment", re.I), "Tanmatra Clinical Nutrition"),
]

# ── Gate 3 · CURRENCY (symbol swap only; log for manual repricing) ─────
CURRENCY = re.compile(r"\$(\s?\d)")

# ── Gate 4 · CLAIMS (no treat/cure/prevent/guarantee) ──────────────────
CLAIM_MAP = [
    (re.compile(r"\breversing\b", re.I), "improving"),
    (re.compile(r"\breverse[sd]?\b", re.I), "improve"),
    (re.compile(r"\bcure[sd]?\b", re.I), "support"),
    (re.compile(r"\bprevent(s|ing)?\b", re.I), "reduce"),
    (re.compile(r"\bguarantee[sd]?\b", re.I), "deliver"),
    (re.compile(r"\bGuaranteed\b"), "Priority"),
    (re.compile(r"clinically proven", re.I), "clinically reviewed"),
    (re.compile(r"optimi[sz]e leptin signaling", re.I), "support steadier satiety"),
]

def run(src: str, dst: str) -> None:
    html = open(src, encoding="utf-8", errors="ignore").read()
    rep = collections.Counter()

    # tokens — case-insensitive hex swap
    for a, b in HEX_MAP.items():
        pat = re.compile(re.escape(a), re.I)
        html, n = pat.subn(b, html)
        if n: rep[f"hex {a}→{b}"] = n
    for pat, b in FONT_MAP:
        html, n = pat.subn(b, html)
        if n: rep[f"font →{b}"] += n

    # split text vs markup so brand/currency/claim edits never touch tags
    parts = re.split(r"(<[^>]+>)", html)
    for i, p in enumerate(parts):
        if p.startswith("<"):
            continue
        for pat, b in BRAND_MAP:
            p, n = pat.subn(b, p)
            if n: rep["brand"] += n
        p, n = CURRENCY.subn(r"₹\1", p)
        if n: rep["currency $→₹ (REPRICE MANUALLY)"] += n
        for pat, b in CLAIM_MAP:
            p, n = pat.subn(b, p)
            if n: rep[f"claim →{b}"] += n
        parts[i] = p
    html = "".join(parts)

    banner = ("<!-- tnm2 PIXEL-DIFF REFERENCE — generated by stitch_retoken.py. "
              "Reference-only: never ship; production = tnm2 components + inline SVG. -->\n")
    open(dst, "w", encoding="utf-8").write(banner + html)

    print(f"wrote {dst}")
    for k, v in rep.most_common():
        print(f"  {v:3d} × {k}")
    if not rep:
        print("  (no substitutions — file was already clean)")

if __name__ == "__main__":
    run(sys.argv[1], sys.argv[2])
