/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/themes/tanmatraTheme.ts
 * Command: astryx theme build lib/themes/tanmatraTheme.ts
 * Generated: 2026-07-27T05:27:30.525Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
