/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/themes/tanmatraTheme.ts
 * Command: astryx theme build lib/themes/tanmatraTheme.ts
 * Generated: 2026-07-27T05:27:30.526Z
 */

/// <reference path="./tanmatra.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const tanmatraTheme: DefinedTheme;
